-- MySQL Script generated by MySQL Workbench
-- Sun Jun 14 00:58:44 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema carwash
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema carwash
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `carwash` DEFAULT CHARACTER SET utf8 ;
USE `carwash` ;

-- -----------------------------------------------------
-- Table `carwash`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carwash`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `birthday` DATETIME NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `cellphone` VARCHAR(15) NOT NULL,
  `phone` VARCHAR(15) NULL,
  `rg` CHAR(10) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carwash`.`vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carwash`.`vehicle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `manufacturer` VARCHAR(50) NOT NULL,
  `plate` VARCHAR(10) NOT NULL,
  `year` INT NOT NULL,
  `color` VARCHAR(25) NULL,
  `description` VARCHAR(250) NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vehicle_client_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `fk_vehicle_client`
    FOREIGN KEY (`client_id`)
    REFERENCES `carwash`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carwash`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carwash`.`services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` DOUBLE(6,2) NOT NULL,
  `date` DATETIME NOT NULL,
  `enter_time` TIME NOT NULL,
  `out_time` TIME NOT NULL,
  `finished` BIT NOT NULL,
  `description` VARCHAR(250) NULL,
  `vehicle_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_vehicle1_idx` (`vehicle_id` ASC) VISIBLE,
  INDEX `fk_order_client1_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_vehicle1`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `carwash`.`vehicle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `carwash`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
